# 创建数组

In [1]:
import numpy as np

In [3]:
np.array([1,2,3],dtype=np.float64)

array([1., 2., 3.])

Numpy 常用基本数据类型：
bool,int8,16,32,64,float16,32,64

In [5]:
# 0填充
np.zeros(10,dtype=np.int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [6]:
# 1填充
np.ones((3,3),dtype=np.float64)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# 任意数值填充
np.full((2,2),3.14)

array([[3.14, 3.14],
       [3.14, 3.14]])

In [11]:
# 类似range的填充
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
# 包括首尾的平均切分
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [36]:
# 设置numpy随机种子
np.random.seed(0)

In [37]:
# 0~1 均匀分布
np.random.random((3,3))

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [41]:
# 0~2均匀分布
np.random.uniform(0,2,(3,3))

array([[1.22419145, 1.23386799, 1.88749616],
       [1.3636406 , 0.7190158 , 0.87406391],
       [1.39526239, 0.12045094, 1.33353343]])

In [22]:
# mean=0,std=1 正态分布
np.random.normal(0,1,(2,2))

array([[ 0.85812183,  2.20257706],
       [-0.34609523, -0.56440172]])

In [27]:
np.random.randint(0,10,(2,2))

array([[1, 9],
       [4, 0]])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 数组属性

In [42]:
x = np.random.random((3,4,5))

In [43]:
# 维数
x.ndim

3

In [44]:
# 每一维的大小
x.shape

(3, 4, 5)

In [45]:
# 总大小
x.size

60

In [46]:
# 数据类型
x.dtype

dtype('float64')

In [48]:
# 按字节的大小（一个数和整个数组的）
x.itemsize  #单个数
x.nbytes  #整个数组

480

# 索引和切片

In [50]:
x[0][1][1]

0.43860151346232035

In [53]:
x[0,1,2]

0.9883738380592262

In [54]:
x[:4]

array([[[0.67063787, 0.21038256, 0.1289263 , 0.31542835, 0.36371077],
        [0.57019677, 0.43860151, 0.98837384, 0.10204481, 0.20887676],
        [0.16130952, 0.65310833, 0.2532916 , 0.46631077, 0.24442559],
        [0.15896958, 0.11037514, 0.65632959, 0.13818295, 0.19658236]],

       [[0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841],
        [0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358],
        [0.03918779, 0.28280696, 0.12019656, 0.2961402 , 0.11872772],
        [0.31798318, 0.41426299, 0.0641475 , 0.69247212, 0.56660145]],

       [[0.26538949, 0.52324805, 0.09394051, 0.5759465 , 0.9292962 ],
        [0.31856895, 0.66741038, 0.13179786, 0.7163272 , 0.28940609],
        [0.18319136, 0.58651293, 0.02010755, 0.82894003, 0.00469548],
        [0.67781654, 0.27000797, 0.73519402, 0.96218855, 0.24875314]]])

In [55]:
x[::2,::2,::2]

array([[[0.67063787, 0.1289263 , 0.36371077],
        [0.16130952, 0.2532916 , 0.24442559]],

       [[0.26538949, 0.09394051, 0.9292962 ],
        [0.18319136, 0.02010755, 0.00469548]]])

In [56]:
x[0,:,:]

array([[0.67063787, 0.21038256, 0.1289263 , 0.31542835, 0.36371077],
       [0.57019677, 0.43860151, 0.98837384, 0.10204481, 0.20887676],
       [0.16130952, 0.65310833, 0.2532916 , 0.46631077, 0.24442559],
       [0.15896958, 0.11037514, 0.65632959, 0.13818295, 0.19658236]])

In [58]:
y = x[0,:,:].copy()

# 变形

In [62]:
# 变形
x = np.arange(9).reshape((3,3))

In [64]:
# 增加一维
x = x[np.newaxis,:]

# 拼接和分裂

In [68]:
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [69]:
z = np.array([3,5,6])
np.concatenate([x,y,z])

array([1, 2, 3, 3, 2, 1, 3, 5, 6])

In [76]:
# 按0维度拼接
grid = np.arange(6).reshape((2,3))
np.concatenate([grid,grid])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [77]:
# 按1维度拼接
np.concatenate([grid,grid],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [78]:
# 垂直拼接 （即按0维度）
np.vstack([grid,grid])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [80]:
# 水平拼接 (即按1维度)
np.hstack([grid,grid])

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [84]:
# 分裂
x = np.arange(9)
x1,x2,x3 = np.split(x,[3,5])

In [87]:
# 垂直分裂
x = np.arange(16).reshape((4,4))
x1,x2 = np.vsplit(x,[2])

In [89]:
# 水平分裂
x1,x2 = np.hsplit(x,[2])

# 通用函数

In [2]:
x = np.arange(4)

In [3]:
x*2

array([0, 2, 4, 6])

In [6]:
x/2

array([0. , 0.5, 1. , 1.5])

In [7]:
x//2

array([0, 0, 1, 1], dtype=int32)

In [8]:
2**x

array([1, 2, 4, 8], dtype=int32)

In [9]:
x+2

array([2, 3, 4, 5])

In [11]:
abs(x-2)

array([2, 1, 0, 1])

In [12]:
np.abs(x-2)

array([2, 1, 0, 1])

In [13]:
x = np.linspace(0,np.pi,3)

In [15]:
np.sin(x)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [17]:
x = [-1,0,1]
np.arcsin(x)

array([-1.57079633,  0.        ,  1.57079633])

np.log  

np.log2

np.log10

np.exp

## 聚合

In [25]:
x = np.arange(1,6)
np.add.reduce(x)

15

In [26]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [27]:
np.multiply.reduce(x)

120

In [28]:
np.sum(x)

15

In [29]:
x.sum()

15

### 聚合函数

In [ ]:
sum  nannum  # 有nan的是NaN安全版本
prod # 乘积
mean # 均值
std # 标准差
var # 方差
min
max
argmin # 索引
argmax 
median
any
all

In [34]:
x = np.random.randint(0,10,6).reshape(2,3)
x.argmin()

2

# 广播

In [51]:
a = np.arange(3)
b = np.arange(3)
a+b

array([0, 2, 4])

In [52]:
a+3

array([3, 4, 5])

In [56]:
a = np.arange(3)
b = np.arange(6).reshape(2,3)
a+b

array([[0, 2, 4],
       [3, 5, 7]])

In [54]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [58]:
y = np.array(x>3,dtype=np.int64)

In [59]:
y

array([[1, 1, 0],
       [0, 0, 1]], dtype=int64)

In [61]:
ind = [(0,0),(0,2)]
y[ind]

<ipython-input-61-7e21079e340d>:2: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  y[ind]


array([1, 0], dtype=int64)